# our CI/CD workflow .yaml file

name: CI/CD workflow

on:
  workflow_dispatch:
    inputs:
      steps:
        description: "Which steps to run?"
        required: true
        type: choice
        options:
          - integration
          - all
        default: all

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    if: ${{ inputs.steps == 'integration' || inputs.steps == 'all' }}
    steps:
      - name: Checkout code repo
        # this action clones current repository to the VM where our job is running
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH #added to PATH

      - name: Install dependencies
        run: uv sync --group integration
        working-directory: polish-sentiment-app

      - name: Run ruff check
        run: uv run ruff check
        working-directory: polish-sentiment-app

      - name: Run pip-audit
        run: uv run pip-audit --vulnerability-service pypi
        working-directory: polish-sentiment-app

      - name: Run PyTest
        run: uv run pytest tests
        working-directory: polish-sentiment-app

  deployment:
    name: Deployment and Optimization
    runs-on: ubuntu-latest
    needs: integration
    if: ${{ inputs.steps == 'all' && needs.integration.result == 'success' }}
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH #added uv to PATH

      - name: Install deployment dependencies
        run: uv sync --group deployment
        working-directory: polish-sentiment-app

      - name: Download model artifacts
        run: uv run python main.py --script download
        working-directory: polish-sentiment-app

      - name: Export model to ONNX
        run: uv run python main.py --script export
        working-directory: polish-sentiment-app

      - name: Build Docker image for ML inference
        run: docker build -t polish-sentiment-app-onnx:latest .
        working-directory: polish-sentiment-app

      # ADDED: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1 # region AWS

      # ADDED: Login to ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      # ADDED: Push Docker image
      - name: Tag and Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: polish-sentiment-app # <- wpisz tutaj nazwę swojego repozytorium ECR
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag polish-sentiment-app-onnx:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
